### ISSUE TITLE
Could not pass event UVTimeEVent to UVVillagers v1.3.9

### ISSUE THREAD

**Issue by 2Fast08** [jcornwellshiel/uvvillagers#51]
Running craftbukkit 1.7.9-R0.3-SNAPSHOT

http://pastebin.com/C00iCp09

**Comment by jcornwellshiel** [comment]
UVVillagers has not been built for 1.7.9 R0.3 yet as I've been ridiculously busy of late. Because it uses org.bukkit.craftbukkit.\* and net.minecraft.\* classes it has to be rebuilt every time bukkit randomly decides to iterate their version numbers. Sorry I haven't gotten to it yet. I have a few minutes free at the moment so I'll rebuild and upload. Link forthcoming.

**Comment by jcornwellshiel** [comment]
http://dev.bukkit.org/bukkit-plugins/uvvillagers/files/35-uvvillagers-1-3-9-for-cb-1-7-9-r0-3/

Let me know if this resolves the issue. If not... let me know, or debug it for me and send a pull request. <3

**Comment by 2Fast08** [comment]
That worked perfectly. I'm learning how to update as I go so I'll try and help out when I can.
